name: Validate JSON Schemas
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    branches:
      - master
jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install NPM dependencies (i.e., ajv)
        run: |
          sudo npm install --loglevel verbose -g yargs ajv-formats@"^1.5.x" ajv-cli@"^4.0.x"
      - name: Validate JSON schema
        run: |
          ajv compile -c ajv-formats -s schema/v5.0/CVE_JSON_5.0.schema
